/*
CREATE TABLE DEPTO (
    CD_DEPTO CHAR(3) NOT NULL PRIMARY KEY,
    NM_DEPTO VARCHAR(40) NOT NULL,
    CD_GERENTE INT(5),
    CD_DEPTO_CTB CHAR(3)
);
CREATE TABLE ATIV (
    CD_ATIV INT(3) NOT NULL PRIMARY KEY,
    NM_SIGLA VARCHAR(12) NOT NULL,
    TX_DESCRICAO VARCHAR(30) NOT NULL
);
CREATE TABLE PROJ (
    CD_PROJ CHAR(6) NOT NULL PRIMARY KEY,
    NM_PROJ VARCHAR(30) NOT NULL,
    CD_DEPTO CHAR(3) NOT NULL,
    CD_RESP INT(5) NOT NULL,
    QT_EQP INT(2) NOT NULL,
    DT_INI DATE,
    DT_FIM DATE,
    FOREIGN KEY (CD_DEPTO) REFERENCES DEPTO(CD_DEPTO),
    FOREIGN KEY (CD_RESP) REFERENCES FUNC(CD_MAT)
);
CREATE TABLE PROJETO_ATIVIDADE (
    CD_PROJ CHAR(6) NOT NULL,
    CD_ATIV INT(3) NOT NULL,
    DT_INI DATE NOT NULL,
    DT_FIM DATE,
    PRIMARY KEY (CD_PROJ, CD_ATIV),
    FOREIGN KEY (CD_PROJ) REFERENCES PROJ(CD_PROJ),
    FOREIGN KEY (CD_ATIV) REFERENCES ATIV(CD_ATIV)
);
CREATE TABLE FUNC (
    CD_MAT INT NOT NULL PRIMARY KEY,
    NM_FUNC VARCHAR(12) NOT NULL,
    NM_SOBRENOME VARCHAR(12) NOT NULL,
    CD_DEPTO CHAR(3) NOT NULL,
    NR_RAMAL INT(4),
    DT_ADM DATE NOT NULL,
    NR_CARGO INT(3) NOT NULL,
    NR_RG INT(2) NOT NULL,
    IN_SEXO CHAR(1) NOT NULL,
    DT_NASC DATE NOT NULL,
    VL_SAL DECIMAL(9,2),
    NM_FOTO VARCHAR(100),
    FOREIGN KEY (CD_DEPTO) REFERENCES DEPTO(CD_DEPTO)
);
CREATE TABLE HST_PROMO (
    CD_MAT INT(5) NOT NULL,
    CD_DEPTO CHAR(3) NOT NULL,
    DT_PROMOCAO DATE NOT NULL,
    VL_SAL DECIMAL(9,2) NOT NULL,
    NR_CARGO INT(3) NOT NULL,
    TX_MOTIVO VARCHAR(200),
    PRIMARY KEY (CD_MAT, CD_DEPTO, NR_CARGO),
    FOREIGN KEY (CD_MAT) REFERENCES FUNC(CD_MAT),
    FOREIGN KEY (CD_DEPTO) REFERENCES DEPTO(CD_DEPTO)
);